default["freeipa"]["ipa_admin_password"] = "adminpw9"
default["freeipa"]["hostname"] = "centos8.example.local"
default["freeipa"]["domain"] = "example.local"
default["freeipa"]["dir_manager_password"] = "dirmanpw8"
default["freeipa"]["realm_name"] = "EXAMPLE.LOCAL"
default["freeipa"]["retries"] = "3"
default["freeipa"]["ipadress"] = "172.18.40.7"
default["freeipa"]["retry_delay"] = "15"
default["freeipa"]["action"] = "append"

